AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Style/AsciiComments:
  Enabled: false

Style/LineLength:
  Max: 76

Style/IfUnlessModifier:
  Enabled: false
