inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'bin/**/*'
    - 'lib/**/*'
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 76

Style/IfUnlessModifier:
  Enabled: false
