sudo: false
language: ruby
cache: bundler
bundler_args: --deployment
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.1
  - 2.3.3
notifications:
  irc:
    use_notice: true
    channels: 
      - 'irc.trpg.net#irc_test'
    on_success: always
    on_failure: always
    template:
      - '%{repository_slug} #%{build_number} %{branch} - %{commit} -> %{result}'
      - '変更履歴: %{compare_url}'
      - 'ステータス: %{build_url}'
  email: false
