sudo: false
language: ruby
cache: bundler
bundler_args: --deployment
rvm:
  - 2.2.7
  - 2.3.1
  - 2.3.4
  - 2.4.1
notifications:
  irc:
    use_notice: true
    channels:
      - 'irc.trpg.net#irc_test'
    on_success: always
    on_failure: always
    template:
      - '%{repository_slug} #%{build_number} %{branch} - %{commit} -> %{result}'
      - '変更履歴: %{compare_url}'
      - 'ステータス: %{build_url}'
  email: false
