# Discord ボットの設定
DiscordBot:
  Token: ''
  ClientID: ''

# 使用するプラグインを列挙する。大文字小文字を区別するので注意
Plugins:
  - DiceRoll
  - RandomGenerator
  - Trpg::Detatoko
  - Bcdice
  - Keyword
  - CreBotHelp

Include:
  - dice_roll
  - random_generator
  - keyword
