# 退出プラグインの設定
Part:
  # 退出時のメッセージ
  # （IRCプロトコルにおける）PART コマンドの引数として使われます。
  PartMessage: 'ご利用ありがとうございました'
  # コマンドを適用しないチャンネルでコマンドが発言されたときのメッセージ
  LockedMessage: 'このチャンネルで .part は使えません。'
  # コマンドを適用しないチャンネル
  PartLock:
    - '#irc_test'
