# 退出プラグインの設定
Part:
  # 退出時のメッセージ
  # （IRCプロトコルにおける）PART コマンドの引数として使われます。
  PartMessage: 'ご利用ありがとうございました'
  # コマンドを無効化するチャンネル
  ExcludeChannels:
    - '#cre'
  # コマンドを無効化したチャンネルで代わりに送信するメッセージ
  NotPartMessage: 'このチャンネルでは退出コマンドを使えないよう設定されています'
