# IRC ボットの設定
IRCBot:
  # 接続する IRC サーバーのホスト名
  Host: irc.example.net

  # 接続するポート
  Port: 6667

  # パスワード。必要なければ null
  Password: pa$$word

  # ニックネーム
  Nick: rgrb_cinch

  # 接続時のユーザー名
  User: rgrb_cinch

  # リアルネーム
  RealName: 汎用ダイスボット RGRB

# 使用するプラグインを列挙する。大文字小文字を区別するので注意
Plugins:
  - DiceRoll
  - Keyword
  - RandomGenerator
