# IRC ボットの設定
IRCBot:
  # 接続する IRC サーバーのホスト名
  Host: irc.example.net

  # 接続するポート
  Port: 6667

  # パスワード。必要なければ null
  Password: pa$$word

  # エンコーディング
  Encoding: UTF-8

  # ニックネーム
  Nick: rgrb_cinch

  # 接続時のユーザー名
  User: rgrb_cinch

  # リアルネーム
  RealName: 汎用ダイスボット RGRB

  # JOIN するチャンネルの一覧
  Channels:
    - ''

# 使用するプラグインを列挙する。大文字小文字を区別するので注意
Plugins:
  - DiceRoll
  - Keyword
  - RandomGenerator
  - CreTwitterCitation
  - CreBotHelp
  - ServerConnectionReport

# Twitter @cre_ne_jp 引用プラグインの設定
CreTwitterCitation:
  # タイムライン監視の間隔（秒）
  # あまり短いとアクセス規制になるので注意
  # 60 以上を推奨
  CheckInterval: 300

  # チェックごとに取得するツイートの最大数
  MaxTweetsPerCheck: 3

  # NOTICE を行うチャンネルの一覧
  ChannelsToSend:
    #- '#cre'

  # Twitter アカウント関連
  Twitter:
    # Twitter ID（@〜）
    ID: cre_ne_jp

    # API キー関連
    # https://apps.twitter.com/ で確認可能
    APIKey: ''
    APISecret: ''
    AccessToken: ''
    AccessTokenSecret: ''

# サーバーリレー監視プラグインの設定
ServerConnectionReport:
  # NOTICE を行なうチャンネルの一覧
  ChannelsToSend:
    - ''
