name: Test and coverage measurement

on:
  push:
    paths-ignore:
      - README.md
  pull_request: {}

jobs:
  test:
    name: "Ruby 3.3: test and coverage measurement"
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Install packages
        run: |
          sudo apt update -qy
          sudo apt install libgdbm6 libgdbm-dev
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: 8310d94ccb41382dfbe0d2fed241c565b33ca01cea938449c4ba0b62500d01e2
        with:
          coverageCommand: bundle exec rake spec
