name: Test

on:
  push:
    paths-ignore:
      - README.md
  pull_request: {}

jobs:
  test:
    name: Test RGRB
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.6
          - 2.7
          - 3.0
          - 3.1
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Install packages
        run: |
          sudo apt update -qy
          sudo apt install libgdbm6 libgdbm-dev
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec
